language: python
python:
  - "2.6"
  - "2.7"
install: "python setup.py install"
script: 
  - "git config --global user.email make@travis.git"
  - "git config --global user.name to_be_happy"
  - "python setup.py flake8"
  - "python setup.py test"
